# Generated by Django 3.2.2 on 2021-05-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_page_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slide_image', models.ImageField(upload_to='banner')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='img',
            field=models.ImageField(default='1.jpg', upload_to='field'),
        ),
    ]
